source "http://rubygems.org"

gem "rails", "4.0.0 "
gem "haml-rails"
gem "jbuilder"
gem "sass-rails"
gem "coffee-rails"

gem "jquery-rails"
gem "mysql"

group :development, :test do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
end

group :test do
  gem 'database_cleaner'
end
